version: '3.2'
networks:
    my-net:
        external: 
            name: my-net
services:
    peer0_org2:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            # placement:
            #     constraints:
            #         - node.hostname == ip-server2privateip
        image: hyperledger/fabric-peer
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: peer node start
        hostname: peer0.org2.example.com
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_PEER_NETWORKID=my-net
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
            - CORE_PEER_ADDRESSAUTODETECT=true
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
            - CORE_LOGGING_LEVEL=DEBUG
            - CORE_LOGGING_GOSSIP=${CORE_LOGGING_GOSSIP}
            - CORE_LOGGING_MSP=DEBUG
            # TLS settings
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
            - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
            - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org2.example.com:9052
            - CORE_PEER_ID=peer0.org2.example.com
            - CORE_PEER_ADDRESS=peer0.org2.example.com:9051
            - CORE_PEER_LOCALMSPID=Org2MSP
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.example.com:10051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:9051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchpeer0org2:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
        volumes:
            - /var/run/:/host/var/run/
            - ../artifacts/channel/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/var/hyperledger/msp
            - ../artifacts/channel/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls:/var/hyperledger/tls
            - ../artifacts/channel/crypto-config/peerOrganizations/org2.example.com/users:/var/hyperledger/users
            - ../artifacts/:/var/hyperledger/config
        # extra_hosts:
        #     - "orderer.example.com:server1publicip"
        #     - "peer0.org1.example.com:server1publicip"
        #     - "peer1.org1.example.com:server1publicip"
        #     - "peer1.org2.example.com:server2publicip"
        #     - "ca.org2.example.com:server2publicip"
        ports:
            - 9051:9051
        networks:
          my-net:
            aliases:
                - peer0.org2.example.com
